REM INSERTING into APPS.NIHGL_NFI_VALIDATION_MSGS
SET DEFINE OFF;
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT009','Duplicate Batch Header or Footer record found in File Name: '||'&'||'FILE_NAME','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT005','Batch Header record is missing in the file','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT010','Batch Detail line Total is: '||'&'||'DETAIL_LINE_TOT (Should not be Zero or Negative), file rejected','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT011','Batch line Total is: '||'&'||'BATCH_LINE_TOT (Should not be Zero or Negatvie), file rejected','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN006','Object Class value is blank','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN007','Object Class is Invalid','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN020','Issue while insert_bc_packets for ope_detail_id','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT003','Batch Number: '||'&'||'BATCH_NUMBER  is not a Valid Batch in the file','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT004','Header Batch Number: '||'&'||'BATCH_HDR_NUM is not matching with Footer Batch Number: '||'&'||'BATCH_FTR_NUM','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT002','Batch Amount Total: '||'&'||'BATCH_AMT_TOT Not Matching with Detail Amount Total : '||'&'||'DETAIL_AMT_TOT','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN008','CAN value is blank','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN005','Accounting Date is not in open/future/closed GL period','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT001','Batch line total: '||'&'||'BATCH_LINE_TOT is not matching with Detail line total : '||'&'||'DETAIL_LINE_TOT','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT006','Batch Footer record is missing in the File','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN030','Accounting period is CLOSED/INVALID for accounting date ('||'&'||'ACCOUNTING_DATE)','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT012','Batch Detail Line Total Amount is: '||'&'||'DETAIL_LINE_TOT (Should not be Zero or Negative), file rejected','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT014','No Valid Batch Header/Footer Records found for the file Name:  '||'&'||'FILE_NAME','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPEBAT013','Batch Total Amount is: '||'&'||'BATCH_AMT_TOT (Should not be Zero or Negatvie), file rejected','File');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN002','Fiscal Year value is Blank','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN003','The Fund in the CAN has been canceled','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN001','Document Number value is Blank','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN010','Transaction Code value is Blank','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN004','CAN is in future Fiscal Year','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN009','CAN is Invalid','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN011','Transaction Code is Invalid','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN012','Reverse Code value is Blank','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN013','Reverse Code is Invalid','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN014','Obligation line does not exists for the combination of Document Ref/Number, Fiscal Year, Batch Number and T-code','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN015','Obligation Balance is either Negative/Zero or Less than Disbursement Amount','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN016','Amounts are not equal for the combination of Document Ref/Number, Fiscal Year and Tcode','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN018','One of the other lines error out for the combination of Document Ref/Number and Fiscal Year','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN023','USSGL Code for Reimbursable Transactions is not Setup in Lookup NIHGL_OPE_TCODES for tcode','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN024','Unable to Derive USSGL Code for Reimbursable Transactions','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN026','ISSUE Deriving CCID and USSGL CODE','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN025','USSGL transaction Code and TCODE mapping not setup in NIHGL_OPE_TCODE_MAPPING Lookup for Others','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN027','ISSUE Deriving CCID','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN029','OPE funds check error','Line');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN017','De-Obligation Amount is greater than the Obligation Balance');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN022','Issue while  updating 3Z Batch as (V)alidated For ope_detail_id: &OPE_DETAIL_ID');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN028','Issue while updating Intf table for  tcode 050 as (V)alidated for ope_detail_id: &OPE_DETAIL_ID');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN031','Corresponding Receivable transaction to reverse does not exists.');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN032','RECEIVABLES BALANCE IS NOT AVAILABLE FOR THE COMBINATION OF DOCUMENT REF/NUMBER, FISCAL YEAR AND BATCH NUMBER.');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN033','TASK Value Is Null');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN034','TASK Is Invalid');
Insert into APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT) values ('ALL','NIHOPETXN035','Expenditure Item Date is Null');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN036','The amount on the reversal line is greater than the available amount for the combination of Batch Number, Doc Ref/Number, CAN, Task, OCC, and CAN FY','Line');
INSERT INTO APPS.NIHGL_NFI_VALIDATION_MSGS (BATCH_NAME,MESSAGE_NAME,MESSAGE_TEXT,ERROR_LEVEL) VALUES ('ALL','NIHOPETXN037','Expenditure Item Date not within the Task dates','Line');




